version: '3.9'
services:
  db:
    container_name: owvision-postgres
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: owvision
    volumes:
      - persistant_data:/data
  api:
    container_name: owvision-api
    image: owvision-api
    restart: always
    env_file: ../api/.docker.env
    depends_on:
      - db
    ports:
      - "3333:3333"
volumes:
  persistant_data: